openapi: 3.0.0
info:
  title: Lowcalibre Recruitment API
  version: 1.0.0
paths:
  /api/apply:
    post:
      summary: Submit application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '200':
          description: OK
  /api/applicants:
    get:
      summary: List applicants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'
components:
  schemas:
    Application:
      type: object
      properties:
        battletag:
          type: string
        char_name:
          type: string
        realm:
          type: string
        class_spec:
          type: string
        desired_role:
          type: string
        notes:
          type: string
        created_at:
          type: string
          format: date-time
